### ISSUE TITLE
fboss_route.py thrift crashing on `list_optics`

### ISSUE THREAD

**Issue by jaymzh** [facebook/fboss#16]
Using a Wedge 40 with pure open-source ONL & FBOSS, `list_optics` crashes with a thrift error:

```
root@onl-wedge:~# fboss_route.py list_optics
Traceback (most recent call last):
  File "/usr/local/bin/fboss_route.py", line 188, in <module>
    args.func(args)
  File "/usr/local/bin/fboss_route.py", line 72, in list_optics
    for key,val in client.getTransceiverInfo(range(1,64)).iteritems():
  File "/usr/local/lib/python2.7/dist-packages/fboss/ctrl/FbossCtrl.py", line 1023, in getTransceiverInfo
    return self.recv_getTransceiverInfo()
  File "/usr/local/lib/python2.7/dist-packages/fboss/ctrl/FbossCtrl.py", line 1040, in recv_getTransceiverInfo
    raise x
thrift.Thrift.TApplicationException: St12out_of_range: flat_map::at key not found
```

**Comment by sonoble** [comment]
I will dig into the issue (since it is possibly something in the way I setup fbthrift in ONL)

**Comment by oridb** [comment]
It's potentially a bug in the fboss agent itself. I'll try fixing the build and pushing an update soon.

**Comment by sonoble** [comment]
Thanks! That would be great.  I am trying to rebuild using the latest fboss but struggling finding the RadixTree.h referenced in this commit https://github.com/facebook/fboss/commit/c77b62795b5ca4b4f54044b345a105933abbc38c

**Comment by oridb** [comment]
Yes, known issue -- I'll have a working build out tomorrow.

**Comment by oridb** [comment]
This should be fixed. Let me know if it's still busted.

**Comment by jaymzh** [comment]
Nope this is still a problem.

**Comment by capveg** [comment]
This code has moved into qsfp_server (for the server side) and the fboss shell on the client side, so none of the code that caused this bug still exists.  I'm going to close this issue.
